name: "Filter QA"
description: "Log QA results for a new filter option."
labels: ["QA-Filter", "Current Release", "Status: In Progress"]
body:
  - type: input
    id: filter_name
    attributes:
      label: Filter Name
      description: Enter the name of the filter being tested.
      placeholder: e.g., Self-employed

  - type: checkboxes
    id: qa_checks
    attributes:
      label: QA Checklist
      description: Check each item after verifying it for this filter.
      options:
        - label: Filter appears in UI
        - label: Filter logic is correct
        - label: Filter can be selected/deselected
        - label: Subtitle and guiding text update correctly
        - label: "Clear all filters" works
        - label: i-button and documentation are correct
        - label: Visualizations and data tables update as expected
        - label: Export/download includes filter selection

  - type: textarea
    id: notes
    attributes:
      label: Notes/Findings
      description: Add any findings, screenshots, or issues discovered during QA.
