name: "Indicator QA"
description: "Log QA results for a specific ACS-based indicator."
labels: ["QA-Indicator", "Current Release", "Status: In Progress"]
body:
  - type: input
    id: indicator_name
    attributes:
      label: Indicator Name
      description: Enter the name of the indicator being tested.
      placeholder: e.g., Percent of individuals with a disability

  - type: checkboxes
    id: qa_checks
    attributes:
      label: QA Checklist
      description: Check each item after verifying it for this indicator.
      options:
        - label: Data source is correct and up to date
        - label: Calculation is accurate
        - label: Tooltip displays correct information
        - label: Data table matches chart and tooltip
        - label: Title and subtitle are consistent
        - label: Filter interactions work as expected
        - label: i-button and technical notes are correct
        - label: Export/download functions include this indicator
        - label: Visual design matches spec
        - label: Error states are handled

  - type: textarea
    id: notes
    attributes:
      label: Notes/Findings
      description: Add any findings, screenshots, or issues discovered during QA.
