name: "QA Test"
description: "Log QA results for a feature or functionality."
labels: ["QA", "Current Release", "Status: In Progress"]
body:
  - type: markdown
    attributes:
      value: |
        Please enter the feature or functionality you are testing as the issue title.
        Example: 'The ACS-based indicator title is revised to reflect use of 2022 data'.

  - type: dropdown
    id: priority
    attributes:
      label: Priority (optional)
      description: "How urgent is this QA check?"
      options:
        - Priority: High
        - Priority: Medium
        - Priority: Low
        - Not Assigned

  - type: checkboxes
    id: browsers_tested
    attributes:
      label: Browsers/Devices Tested
      description: |
        Check all browsers/devices you actually tested.
        **If you tested a browser/device and do not check it as passed below, it will be considered a failure.**
      options:
        - label: Chrome - desktop
        - label: Safari - desktop
        - label: Firefox - desktop
        - label: Chrome - mobile
        - label: Safari - mobile
        - label: Firefox - mobile

  - type: checkboxes
    id: browsers_passed
    attributes:
      label: Browsers/Devices Passed
      description: |
        Check all browsers/devices that passed all tests for this feature.
      options:
        - label: Chrome - desktop
        - label: Safari - desktop
        - label: Firefox - desktop
        - label: Chrome - mobile
        - label: Safari - mobile
        - label: Firefox - mobile

  - type: textarea
    id: notes
    attributes:
      label: Notes and Issues
      description: |
        List any browsers/devices that failed, details, and steps to reproduce.
        You can also drag and drop screenshots here after submitting the issue.

  - type: markdown
    attributes:
      value: |
        **Note:** The QA Status label (`QA Status: Pass` or `QA Status: Fail`) will be set automatically based on your selections above.
