name: "QA Test: [Feature/Functionality]"
description: "Log QA results for a feature or functionality."
title: "QA: [Feature/Functionality Name]"
labels: ["QA", "Current Release", "Status: In Progress"]
body:
  - type: input
    id: feature
    attributes:
      label: Feature/Functionality
      description: "What are you testing?"
      placeholder: "e.g., The ACS-based indicator title is revised to reflect use of 2022 data"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (optional)
      description: "How urgent is this QA check?"
      options:
        - Priority: High
        - Priority: Medium
        - Priority: Low
        - Not Assigned

  - type: checkboxes
    id: browsers_tested
    attributes:
      label: Browsers/Devices Tested (check all that apply)
      options:
        - label: Chrome - desktop
        - label: Safari - desktop
        - label: Firefox - desktop
        - label: Chrome - mobile
        - label: Safari - mobile
        - label: Firefox - mobile

  - type: checkboxes
    id: browsers_passed
    attributes:
      label: Browsers/Devices Passed (check all that apply)
      options:
        - label: Chrome - desktop
        - label: Safari - desktop
        - label: Firefox - desktop
        - label: Chrome - mobile
        - label: Safari - mobile
        - label: Firefox - mobile

  - type: textarea
    id: notes
    attributes:
      label: Notes and Issues
      description: "Describe any issues, device used, and how to reproduce, if applicable."

  - type: markdown
    attributes:
      value: |
        **Note:** The overall QA status (`QA Status: Pass` or `QA Status: Fail`) will be set automatically based on your selections above.
