name: "QA Test: [Feature/Functionality]"
description: "Log QA results for a feature/functionality across browsers/devices."
title: "QA: [Feature/Functionality Name]"
labels: ["QA", "Status: In Progress"]
body:
  - type: input
    id: feature
    attributes:
      label: Feature/Functionality
      description: "Describe the feature or functionality being tested."
      placeholder: "e.g., The ACS-based indicator title is revised to reflect use of 2022 data"
    validations:
      required: true

  - type: checkboxes
    id: browsers_tested
    attributes:
      label: Browsers/Devices Tested (check all that apply)
      options:
        - label: Chrome - desktop
        - label: Safari - desktop
        - label: Firefox - desktop
        - label: Chrome - mobile
        - label: Safari - mobile
        - label: Firefox - mobile

  - type: checkboxes
    id: browsers_passed
    attributes:
      label: Browsers/Devices Passed (check all that apply)
      options:
        - label: Chrome - desktop
        - label: Safari - desktop
        - label: Firefox - desktop
        - label: Chrome - mobile
        - label: Safari - mobile
        - label: Firefox - mobile

  - type: textarea
    id: notes
    attributes:
      label: Notes and Issues
      description: "Describe any issues, device used, and how to reproduce, if applicable."
