name: Auto-label QA Status

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label-qa-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set QA Status Label
        uses: actions/github-script@v7.0.1
        with:
          script: |
            // Helper to extract checked items from markdown checkbox lists
            function getCheckedItems(body, sectionLabel) {
              const regex = new RegExp(sectionLabel + '[\\s\\S]*?(?:- \\[[ xX]\\] .+)+', 'm');
              const section = body.match(regex);
              if (!section) return [];
              return Array.from(section[0].matchAll(/- \[[xX]\] (.+)/g)).map(m => m[1].trim());
            }

            const issueBody = context.payload.issue.body;

            // Extract tested and passed browsers/devices
            const tested = getCheckedItems(issueBody, "Browsers/Devices Tested");
            const passed = getCheckedItems(issueBody, "Browsers/Devices Passed");

            // Determine if all tested browsers passed
            const allPassed = tested.length > 0 && tested.every(browser => passed.includes(browser));

            // Define labels
            const passLabel = "QA Status: Pass";
            const failLabel = "QA Status: Fail";
            const inProgressLabel = "Status: In Progress";

            // Current labels on the issue
            const currentLabels = context.payload.issue.labels.map(label => label.name);

            // Prepare labels to add and remove
            let labelsToAdd = [];
            let labelsToRemove = [];

            if (allPassed) {
              labelsToAdd.push(passLabel);
              labelsToRemove.push(failLabel, inProgressLabel);
            } else {
              labelsToAdd.push(failLabel);
              labelsToRemove.push(passLabel, inProgressLabel);
            }

            // Remove old labels and add new ones
            const updatedLabels = currentLabels.filter(label => !labelsToRemove.includes(label)).concat(
              labelsToAdd.filter(label => !currentLabels.includes(label))
            );

            // Update the issue labels
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: updatedLabels
            });
