name: Auto-label QA Status

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label-qa-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set QA Status Labels
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';
            const qaLabels = ['QA-Breakdown', 'QA-Indicator', 'QA-Filter'];
            const statusLabels = ['QA Status: Pass', 'QA Status: Fail', 'Status: In Progress'];

            // Only operate if the issue has a QA label
            const hasQALabel = issue.labels.some(l => qaLabels.includes(l.name));
            if (!hasQALabel) {
              return;
            }

            // Find all checkboxes in the QA Checklist section
            // This regex matches all markdown checkboxes in the body
            const checklistMatches = body.match(/- \[[ xX]\] .+/g) || [];
            const total = checklistMatches.length;
            const checked = checklistMatches.filter(line => line.startsWith('- [x]') || line.startsWith('- [X]')).length;

            // Determine which status label to apply
            let labelToAdd = 'Status: In Progress';
            if (total > 0 && checked === total) {
              labelToAdd = 'QA Status: Pass';
            } else if (total > 0 && checked < total) {
              labelToAdd = 'QA Status: Fail';
            }

            // Remove old status labels
            const currentLabels = issue.labels.map(l => l.name);
            const newLabels = currentLabels.filter(l => !statusLabels.includes(l)).concat(labelToAdd);

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: newLabels
            });
